# Generated by Django 5.0.4 on 2024-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_text_post_body_1_post_body_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Caption_of_image_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Caption_of_image_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Caption_of_image_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
