# Generated by Django 5.0.6 on 2024-07-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_caption_of_image_1_post_caption_of_image_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Body_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Body_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Caption_of_image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Caption_of_image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Caption_of_image_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_3',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='Blog.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
