# Generated by Django 5.0.6 on 2024-07-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_post_category_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
