# Generated by Django 5.0.6 on 2024-08-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='Blog.post')),
            ],
        ),
    ]
