# Generated by Django 5.0.6 on 2024-08-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_remove_post_trending_remove_post_views_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
