# Generated by Django 5.0.6 on 2024-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_tag_post_views_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
