# Generated by Django 5.0.6 on 2024-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_post_last_viewed_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='BlogCover',
            field=models.ImageField(upload_to='blog_covers/'),
        ),
    ]
