# Generated by Django 5.0.6 on 2024-08-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_alter_comment_author_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
