# Generated by Django 5.1 on 2024-09-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
